name: Hourly Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

env:
  GIT_AUTHOR_NAME: actions-user
  GIT_AUTHOR_EMAIL: action@github.com
  GIT_COMMITTER_NAME: actions-user
  GIT_COMMITTER_EMAIL: action@github.com

jobs:
  check:
    name: Check for updates in LobeChat
    runs-on: ubuntu-latest
    outputs:
      new_commit: ${{ steps.check-updates.outputs.new_commit }}
      fetched_commit: ${{ steps.check-updates.outputs.fetched_commit }}
      last_commit: ${{ steps.check-updates.outputs.last_commit }}

    steps:
      - name: Check out patch repo
        uses: actions/checkout@v4
      - name: Clone and check out `lobehub/lobe-chat`
        run: |
          cd ../
          git clone https://github.com/lobehub/lobe-chat.git --depth 5
          cd ./lobe-chat
          git checkout HEAD
      - name: Check latest commit hash of Lobe Chat
        id: check-updates
        working-directory: ../lobe-chat
        run: |
          FETCHED_COMMIT=$(git rev-parse HEAD)
          LAST_COMMIT=$(cat ../lobe-msm-build/lobe-chat-HEAD | tr -d '\n')
          if [ "$FETCHED_COMMIT" != "$LAST_COMMIT" ]; then
            echo "new_commit=true" >> $GITHUB_OUTPUT
            echo "fetched_commit=$FETCHED_COMMIT" >> $GITHUB_OUTPUT
            echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT

            echo "Fetched Commit: $FETCHED_COMMIT"
          else
            echo "new_commit=false" >> $GITHUB_OUTPUT
          fi

  release-notes:
    name: Release notes
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.new_commit == 'true'
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clone and check out `lobehub/lobe-chat`
        run: |
          cd ../
          git clone https://github.com/lobehub/lobe-chat.git --depth 500
          cd ./lobe-chat
          git checkout HEAD
      - name: Find relevant commits and tags
        id: tags
        working-directory: ../lobe-chat
        run: |
          FETCHED_COMMIT=${{ needs.check.outputs.fetched_commit }}
          LAST_COMMIT=${{ needs.check.outputs.last_commit }}
          echo "Fetching releases between $LAST_COMMIT and $FETCHED_COMMIT"
          if ! git cat-file -t "$LAST_COMMIT" &>/dev/null; then
            echo "$LAST_COMMIT is not a valid commit. Skipping release notes fetch."
            exit 0
          fi

          COMMITS=$(git log --pretty=format:"%H" "$LAST_COMMIT..$FETCHED_COMMIT" | tr '\n' ' ')
          echo "Commits between: $COMMITS"

          FUTURE_COMMIT=$(git log --pretty=format:"%H" $FETCHED_COMMIT..HEAD --reverse | head -1)
          if [ -n "$FUTURE_COMMIT" ]; then
            TAGS=$(git tag --contains "$LAST_COMMIT" --no-contains "$FUTURE_COMMIT")
          else
            TAGS=$(git tag --contains "$LAST_COMMIT")
          fi

          if [ -z "$TAGS" ]; then
            echo "No tags found between specified commits."
            exit 0
          fi

          TAGS=$(echo "$TAGS" | tr '\n' ' ')

          echo "Tags between the specified commits: $TAGS"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "TAGS=$TAGS" >> $GITHUB_ENV
      - name: Fetch release notes
        if: steps.tags.outputs.tags != ''
        run: |
          curl -s "https://api.github.com/repos/lobehub/lobe-chat/releases" > releases.json
          node -e "
            const fs = require('fs');
            const releases = JSON.parse(fs.readFileSync('releases.json', 'utf-8'));
            const tags = process.env.TAGS.split(/\s+/);

            const releaseNotes = releases
              .filter(release => tags.includes(release.tag_name))
              .map(
                release => release.body.replaceAll(
                  '<div align=\"right\">\n\n[![](https://img.shields.io/badge/-BACK_TO_TOP-151515?style=flat-square)](#readme-top)\n\n</div>',
                  ''
                )
              ).reverse().join('\\n').replaceAll('\\n\\n', '\\n');

            const output = [
              '## Release Notes',
              releaseNotes || 'No new releases found between specified commits.'
            ].join('\\n');

            fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, output);
          "


  build-image:
    name: Build
    needs: check
    if: needs.check.outputs.new_commit == 'true'
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
    with:
      update_run_id: ${{ github.run_id }}

  update-commit-hash:
    name: Update commit hash file
    runs-on: ubuntu-latest
    needs: [check, build-image]

    steps:
      - uses: actions/checkout@v4
      - run: |
          FETCHED_COMMIT=${{ needs.check.outputs.fetched_commit }}
          echo "Updating last known commit to: $FETCHED_COMMIT"
          echo "$FETCHED_COMMIT" > ./lobe-chat-HEAD

          git add .
          git commit -m "Update lobe-chat-HEAD to: $FETCHED_COMMIT"
          git push
