name: Hourly Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

env:
  GIT_AUTHOR_NAME: actions-user
  GIT_AUTHOR_EMAIL: action@github.com
  GIT_COMMITTER_NAME: actions-user
  GIT_COMMITTER_EMAIL: action@github.com

jobs:
  check:
    name: Check lobe-chat updates
    runs-on: ubuntu-latest
    outputs:
      new_commit: ${{ steps.check-updates.outputs.new_commit }}

    steps:
      - name: Check out the patch repo
        uses: actions/checkout@v4
      - name: Clone and checkout lobe-chat repo
        run: |
          cd ../
          git clone https://github.com/lobehub/lobe-chat.git --depth 50
          cd ./lobe-chat
          git checkout HEAD
      - name: Check if lobe-chat repo got updates
        id: check-updates
        working-directory: ../lobe-chat
        run: |
          FETCHED_COMMIT=$(git rev-parse HEAD)
          LAST_COMMIT=$(cat ../lobe-msm-build/lobe-chat-HEAD | tr -d '\n')
          if [ "$FETCHED_COMMIT" != "$LAST_COMMIT" ]; then
            echo "new_commit=true" >> $GITHUB_OUTPUT
            echo "FETCHED_COMMIT=$FETCHED_COMMIT" >> $GITHUB_ENV
            echo "Fetched Commit: $FETCHED_COMMIT"
          else
            echo "new_commit=false" >> $GITHUB_OUTPUT
          fi
      - name: Update stored commit
        if: steps.check-updates.outputs.new_commit == 'true'
        run: |
          echo "Updating last known commit to: $FETCHED_COMMIT"
          echo "$FETCHED_COMMIT" > ./lobe-chat-HEAD

          git add .
          git commit -m "Update lobe-chat-HEAD to: $FETCHED_COMMIT"
          git push

  build-image:
    name: Build new image
    needs: check
    if: ${{ needs.check.outputs.new_commit }} == 'true'
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
